# Generated by Django 3.1.6 on 2021-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontypes',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='stats',
            name='pokemons',
            field=models.ManyToManyField(through='pokemons.PokemonStats', to='pokemons.Pokemons'),
        ),
        migrations.AddField(
            model_name='types',
            name='pokemons',
            field=models.ManyToManyField(through='pokemons.PokemonTypes', to='pokemons.Pokemons'),
        ),
        migrations.AlterField(
            model_name='pokemontypes',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pokemontypes',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='types',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='types',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
