# Generated by Django 3.1.6 on 2021-03-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_pokemonevolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonevolution',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonevolution',
            name='pokemonEvolution1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution1', to='pokemons.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonevolution',
            name='pokemonEvolution2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution2', to='pokemons.pokemon'),
        ),
        migrations.AlterModelTable(
            name='pokemonevolution',
            table='pokemon_evolutions',
        ),
    ]
